"""Seed & extend randomized assessment question banks for all 24 courses.

For courses with existing full quizzes (10 full courses), we augment with domain
questions. For catalog-only courses (14), we seed a full bank of 15-18 questions.

Idempotent: uses a stable question_id derived from slug + question hash so we can
upsert without duplicates on re-run.
"""
from __future__ import annotations

import hashlib
from typing import List

from core import db, logger
from models import QuizQuestion


def _qid(slug: str, question_text: str) -> str:
    """Stable ID so re-seeds don't duplicate."""
    h = hashlib.md5(f"{slug}::{question_text}".encode()).hexdigest()[:12]
    return f"q-{slug[:20]}-{h}"


def _build(slug: str, items: List[dict]) -> List[dict]:
    out = []
    for it in items:
        q = QuizQuestion(
            id=_qid(slug, it["question"]),
            question=it["question"],
            type=it.get("type", "mcq"),
            options=it["options"],
            correct=it["correct"],
            explanation=it.get("explanation", ""),
            difficulty=it.get("difficulty", "intermediate"),
        )
        out.append(q.model_dump())
    return out


# ---------------------------------------------------------------------------
# Question banks per course slug.
# Keep 15-18 questions per course. Mix mcq / multi / true_false / scenario.
# ---------------------------------------------------------------------------

BANKS: dict[str, List[dict]] = {
    # ---------------- Foundations (already has 12 baked in) ----------------
    "agentic-ai-foundations": [
        {"question": "Which loop best describes an agent's core cycle?",
         "options": ["Read → Print → Loop", "Perceive → Reason → Act → Reflect", "Encode → Decode → Sample", "Train → Infer → Deploy"],
         "correct": [1], "explanation": "The canonical agent loop is perceive/reason/act/reflect."},
        {"question": "Which memory tier stores learned skills and procedures?",
         "options": ["Short-term", "Episodic", "Semantic", "Procedural"], "correct": [3]},
        {"question": "Select ALL patterns that improve tool reliability.",
         "type": "multi",
         "options": ["Idempotent design", "Exponential backoff retries", "Silent error swallow", "Typed argument contracts"],
         "correct": [0, 1, 3]},
        {"question": "Which framework provides deterministic state-machine execution for agents?",
         "options": ["LangGraph", "CrewAI", "AutoGen", "LlamaIndex"], "correct": [0]},
        {"question": "Scenario: An agent must summarize 10 patient records with PHI. Which action is FIRST?",
         "type": "scenario",
         "options": ["Ship to public LLM", "Apply HIPAA-compliant redaction & routing before inference", "Cache the raw PHI in vector DB", "Use temperature 1.0 for creativity"],
         "correct": [1]},
        {"question": "Multi-agent systems are ALWAYS preferable to single-agent designs.",
         "type": "true_false", "options": ["True", "False"], "correct": [1]},
    ],
    # ---------------- Prompt Engineering ----------------
    "prompt-engineering-mastery": [
        {"question": "Which prompting technique explicitly reasons step-by-step before final answer?",
         "options": ["Zero-shot", "Few-shot", "Chain-of-Thought", "Beam search"], "correct": [2]},
        {"question": "What is the primary benefit of few-shot prompting?",
         "options": ["Reduces model size", "Provides in-context examples that anchor format & style",
                     "Fine-tunes weights", "Eliminates hallucination"], "correct": [1]},
        {"question": "Select ALL prompt-engineering anti-patterns.",
         "type": "multi",
         "options": ["Vague instructions", "Concatenating untrusted user input into system role",
                     "Using explicit output schemas", "Assuming the model knows recent events"],
         "correct": [0, 1, 3]},
        {"question": "Self-consistency sampling improves reasoning by:",
         "options": ["Reducing temperature to 0", "Sampling N reasoning paths and voting the majority answer",
                     "Prompt caching", "Reranking token probabilities"], "correct": [1]},
        {"question": "Structured output (JSON schema) prompting is BEST when:",
         "options": ["Users want prose", "Downstream code parses the response",
                     "Creativity is prioritized", "Latency doesn't matter"], "correct": [1]},
        {"question": "ReAct combines which two paradigms?",
         "options": ["Rag + Actions", "Reasoning + Acting (tool calls)",
                     "Retrieval + Alignment", "Reflection + Aggregation"], "correct": [1]},
        {"question": "Prompt injection can be mitigated by dual-LLM patterns.",
         "type": "true_false", "options": ["True", "False"], "correct": [0]},
        {"question": "What role does system prompt play vs. user prompt?",
         "options": ["System sets persona/rules; user submits the task",
                     "They are interchangeable", "System is optional decoration",
                     "User prompt is always ignored"], "correct": [0]},
        {"question": "Scenario: A legal AI must cite sources for every claim. Best pattern:",
         "type": "scenario",
         "options": ["Higher temperature", "Structured JSON output with mandatory 'citation' field validated post-hoc",
                     "Remove system prompt", "Ignore hallucinations"], "correct": [1]},
        {"question": "Which sampling parameter most influences creativity vs. determinism?",
         "options": ["max_tokens", "temperature", "top_k only", "stop sequences"], "correct": [1]},
        {"question": "Prefix caching primarily reduces:",
         "options": ["Model accuracy", "Repeated prompt token cost", "Model size", "Context window"], "correct": [1]},
        {"question": "Which technique produces the MOST reliable extraction from unstructured docs?",
         "options": ["Free-form prompt", "Structured schema + few-shot + validation loop",
                     "Random seed 42", "Chat memory only"], "correct": [1]},
        {"question": "Meta-prompting refers to:",
         "options": ["Fine-tuning", "Prompting a model to generate or improve prompts",
                     "Using multiple providers", "Chain-of-thought"], "correct": [1]},
        {"question": "Select ALL benefits of explicit output schemas.",
         "type": "multi",
         "options": ["Deterministic parsing", "Reduced formatting drift",
                     "Increased hallucination", "Better downstream integration"],
         "correct": [0, 1, 3]},
        {"question": "Tree-of-Thought is BEST used for:",
         "options": ["Trivial factoids", "Problems requiring exploration of multiple reasoning branches",
                     "Reducing token cost", "One-shot classification"], "correct": [1]},
    ],
    # ---------------- RAG ----------------
    "rag-enterprise": [
        {"question": "Which retrieval strategy combines dense + sparse for best precision?",
         "options": ["Pure vector", "Hybrid (BM25 + vector)", "Random", "Regex only"], "correct": [1]},
        {"question": "What is Contextual Retrieval (Anthropic 2024) primarily designed to solve?",
         "options": ["Latency", "Chunks losing document-level context",
                     "Model quantization", "Cost of embeddings"], "correct": [1]},
        {"question": "Select ALL benefits of RAG over fine-tuning for knowledge injection.",
         "type": "multi",
         "options": ["Freshness / easy updates", "Citations & auditability",
                     "Right-to-forget compliance", "Zero inference cost"],
         "correct": [0, 1, 2]},
        {"question": "A reranker is used to:",
         "options": ["Generate embeddings", "Reorder top-K candidates by relevance to the query",
                     "Fine-tune the LLM", "Cache prompts"], "correct": [1]},
        {"question": "Which is a common chunking failure mode?",
         "options": ["Chunks too small losing context; too large hurting precision",
                     "Model overload", "GPU memory", "Loss of embeddings"], "correct": [0]},
        {"question": "RAGAS evaluates which of the following?",
         "type": "multi",
         "options": ["Faithfulness", "Answer relevance", "Context precision", "Model perplexity"],
         "correct": [0, 1, 2]},
        {"question": "Semantic caching in RAG:",
         "options": ["Rewrites the query", "Serves prior answers to semantically similar queries",
                     "Replaces the vector DB", "Only works with SQL"], "correct": [1]},
        {"question": "For sub-second retrieval over 100M docs, which vector index is standard?",
         "options": ["Linear scan", "HNSW / IVF-PQ", "Bubble sort", "MapReduce"], "correct": [1]},
        {"question": "GraphRAG differentiates itself by:",
         "options": ["Using no embeddings", "Adding entity-relationship graph traversal for multi-hop reasoning",
                     "Being cheaper", "Only working on text"], "correct": [1]},
        {"question": "Scenario: RAG returns correct docs but LLM invents facts. Most likely fix:",
         "type": "scenario",
         "options": ["Larger K", "Stricter grounding prompt + faithfulness eval + citation-required output schema",
                     "Change vector DB", "Lower temperature to 0 only"], "correct": [1]},
        {"question": "Query rewriting (HyDE) generates:",
         "options": ["A random query", "A hypothetical answer used as the retrieval query",
                     "The final answer", "The system prompt"], "correct": [1]},
        {"question": "Metadata filtering during retrieval is critical for:",
         "options": ["Cost", "Multi-tenant isolation & permission-aware search",
                     "Speed only", "Chunking"], "correct": [1]},
        {"question": "Which is TRUE about embedding model choice?",
         "options": ["All models perform equally", "Domain-specific embeddings materially improve recall",
                     "Larger dim always better", "Cheaper = better"], "correct": [1]},
        {"question": "Chunk size for legal/regulatory RAG typically:",
         "options": ["<50 tokens", "300-800 tokens with overlap", "Whole document",
                     "Random size"], "correct": [1]},
        {"question": "Late chunking refers to:",
         "options": ["Chunking at query time", "Embedding whole documents then slicing embeddings",
                     "Chunking after the LLM answers", "Manual chunking"], "correct": [1]},
    ],
    # ---------------- Multi-Agent ----------------
    "multi-agent-systems": [
        {"question": "Google's A2A protocol standardizes:",
         "options": ["Model weights", "Cross-vendor agent interoperability (skills, tasks, artifacts)",
                     "Vector DB APIs", "GPU allocation"], "correct": [1]},
        {"question": "Supervisor pattern is best when:",
         "options": ["Trivial parallelism", "A central planner must decompose & delegate to specialist agents",
                     "Only one tool exists", "Regulated tasks forbid delegation"], "correct": [1]},
        {"question": "Select ALL common multi-agent failure modes.",
         "type": "multi",
         "options": ["Deadlock / loop", "Cost runaway", "Conflicting decisions", "Guaranteed convergence"],
         "correct": [0, 1, 2]},
        {"question": "Blackboard architecture uses:",
         "options": ["Shared knowledge store readable/writable by all agents",
                     "Peer-to-peer only", "Single agent", "Random routing"], "correct": [0]},
        {"question": "Cost budgets should be enforced per:",
         "options": ["Global only", "Session, tenant, and task", "Never enforced",
                     "Only in dev"], "correct": [1]},
        {"question": "Best framework for role-based collaboration crews:",
         "options": ["CrewAI", "PyTorch", "TensorFlow", "Numpy"], "correct": [0]},
        {"question": "Handoff between agents should preserve:",
         "type": "multi",
         "options": ["Task goal", "Prior context/summary", "Tool call history", "Random state"],
         "correct": [0, 1, 2]},
        {"question": "Arbiter agents are used to:",
         "options": ["Resolve conflicting outputs from peer agents", "Store embeddings",
                     "Optimize CUDA", "Log tokens"], "correct": [0]},
        {"question": "Scenario: 3-agent crew deadlocks arguing over a decision. Best fix:",
         "type": "scenario",
         "options": ["Add more agents", "Add timeout + arbiter agent + max-turns cap",
                     "Increase temperature", "Ignore and retry infinitely"], "correct": [1]},
        {"question": "AutoGen frames orchestration as:",
         "options": ["Message-passing conversations between agents",
                     "Static DAGs", "Terraform", "Kubernetes CRDs"], "correct": [0]},
        {"question": "Hierarchical patterns are appropriate when:",
         "options": ["Tasks have clear parent-child decomposition",
                     "All tasks are equal", "Only one agent needed",
                     "No planning is possible"], "correct": [0]},
        {"question": "Observability in multi-agent systems requires:",
         "type": "multi",
         "options": ["Distributed traces per agent", "Per-agent cost/latency",
                     "Message logs with correlation IDs", "Randomly sampled logs only"],
         "correct": [0, 1, 2]},
        {"question": "Multi-agent overhead is typically worth it for tasks under 30 seconds.",
         "type": "true_false", "options": ["True", "False"], "correct": [1]},
        {"question": "Agent-to-agent handshake in A2A begins with:",
         "options": ["Skill discovery via agent card", "Payment", "GPU allocation", "OAuth token"], "correct": [0]},
        {"question": "Which is the strongest signal to use multi-agent design?",
         "options": ["Clean role decomposition + parallelizable subtasks",
                     "Small prompts", "Cost pressure", "Trivial workflow"], "correct": [0]},
    ],
    # ---------------- AI Governance ----------------
    "ai-governance-compliance": [
        {"question": "Which regulation classifies AI systems by risk tier (unacceptable, high, limited, minimal)?",
         "options": ["GDPR", "EU AI Act", "CCPA", "PIPEDA"], "correct": [1]},
        {"question": "NIST AI RMF has how many core functions?",
         "options": ["3", "4 (Govern, Map, Measure, Manage)", "5", "6"], "correct": [1]},
        {"question": "ISO/IEC 42001 is:",
         "options": ["A prompt technique", "The first international AI management system standard",
                     "A GPU spec", "A vector DB"], "correct": [1]},
        {"question": "Under GDPR Article 22, individuals have a right to:",
         "options": ["Free AI use", "Meaningful information about + human review of automated decisions",
                     "Model weights", "GPU access"], "correct": [1]},
        {"question": "Select ALL documentation typically required for high-risk AI systems.",
         "type": "multi",
         "options": ["Model card", "Data sheet", "Risk assessment", "Audit trail"],
         "correct": [0, 1, 2, 3]},
        {"question": "The Colorado AI Act primarily targets:",
         "options": ["Consumer AI", "Consequential AI systems making decisions about individuals",
                     "GPU exports", "Ad tech only"], "correct": [1]},
        {"question": "Model cards should include:",
         "type": "multi",
         "options": ["Intended use", "Limitations", "Training data characteristics", "Marketing claims only"],
         "correct": [0, 1, 2]},
        {"question": "New York LL 144 targets:",
         "options": ["Employment automated decision tools requiring bias audit",
                     "AI art", "Bitcoin mining", "Autonomous vehicles"], "correct": [0]},
        {"question": "Scenario: HR uses a resume-scoring AI in NYC. Compliance requires:",
         "type": "scenario",
         "options": ["Nothing", "Public bias audit + candidate notice under LL 144",
                     "Only training the model on public data", "Blockchain anchoring"], "correct": [1]},
        {"question": "EU AI Act obligations for General-Purpose AI (GPAI) with systemic risk include:",
         "type": "multi",
         "options": ["Model evaluation", "Systemic risk assessment", "Cybersecurity measures", "None"],
         "correct": [0, 1, 2]},
        {"question": "Which is NOT typically an AI governance committee responsibility?",
         "options": ["Reviewing high-risk deployments", "Setting policy", "Writing kernel drivers",
                     "Escalating incidents"], "correct": [2]},
        {"question": "The EU AI Act's territorial scope includes providers offering AI systems in the EU market.",
         "type": "true_false", "options": ["True", "False"], "correct": [0]},
        {"question": "Impact assessments should occur:",
         "options": ["Post-launch only", "Before deployment for high-risk uses AND periodically thereafter",
                     "Never", "Only if regulator asks"], "correct": [1]},
        {"question": "Which artifact tracks data-provenance for training sets?",
         "options": ["Model card", "Datasheet for datasets", "Kubernetes manifest", "Terraform state"], "correct": [1]},
        {"question": "Best forum to align AI risk with enterprise ERM:",
         "options": ["Standalone AI board", "Integrated with existing enterprise risk committee",
                     "Marketing team", "External vendor"], "correct": [1]},
    ],
    # ---------------- Banking ----------------
    "agentic-ai-banking": [
        {"question": "SR 11-7 is issued by which regulator?",
         "options": ["FDA", "US Federal Reserve (model risk management)", "SEC", "FINRA"], "correct": [1]},
        {"question": "Which agent workflow is HIGHEST value for retail banking today?",
         "options": ["AGI", "Automated dispute resolution + KYC augmentation",
                     "Weather forecasting", "Meme generation"], "correct": [1]},
        {"question": "Select ALL banking-specific agent guardrails.",
         "type": "multi",
         "options": ["Fair lending audits", "PII/PCI redaction", "Human-in-the-loop for account actions",
                     "Auto-approve loans without review"],
         "correct": [0, 1, 2]},
        {"question": "Fair lending under ECOA/Reg B requires:",
         "options": ["No auditability", "Documented adverse-action reasoning with protected-class impact review",
                     "Random denial", "Ignoring bias"], "correct": [1]},
        {"question": "Basel III operational risk considers AI risks under:",
         "options": ["Credit risk only", "Operational risk / model risk",
                     "Interest rate risk", "None"], "correct": [1]},
        {"question": "Scenario: Agent auto-answers 'wire transfer' request. Best pattern:",
         "type": "scenario",
         "options": ["Fully autonomous transfer", "Draft the transfer, require human approval + fraud check",
                     "Charge extra fees", "Skip logs"], "correct": [1]},
        {"question": "AML transaction monitoring benefits most from:",
         "options": ["LLM narrative generation for SAR + graph-based typology detection",
                     "Trivia bots", "Meme generation", "Ad targeting"], "correct": [0]},
        {"question": "Bank Secrecy Act filings can be:",
         "type": "multi",
         "options": ["Drafted by agents", "Reviewed by humans", "Filed without review",
                     "Audited"], "correct": [0, 1, 3]},
        {"question": "Explainability requirement for credit decisions is anchored in:",
         "options": ["Cool factor", "ECOA + FCRA + Reg B adverse-action notices",
                     "SEC only", "Nothing"], "correct": [1]},
        {"question": "SR 11-7 lifecycle stage a bank must NOT skip:",
         "options": ["Development", "Validation", "Independent validation & ongoing monitoring",
                     "Deprecation"], "correct": [2]},
        {"question": "PCI-DSS impacts agents that touch:",
         "options": ["Marketing copy", "Cardholder data", "Weather data", "Music"], "correct": [1]},
        {"question": "Which risk is UNIQUE to LLM-powered banking agents?",
         "options": ["Data poisoning of training corpus + prompt injection into customer chat",
                     "Interest rate risk", "Currency risk", "Reputational only"], "correct": [0]},
        {"question": "For agent-generated SARs, human review is:",
         "type": "true_false", "options": ["True — mandatory before filing", "False — never needed"], "correct": [0]},
        {"question": "Banking KYC augmentation via agents typically improves:",
         "type": "multi",
         "options": ["Onboarding time", "Document-parsing accuracy", "Manual review capacity",
                     "None"], "correct": [0, 1, 2]},
        {"question": "OCC guidance on AI risks emphasizes:",
         "options": ["Cost reduction only", "Governance, third-party risk, and model risk",
                     "Marketing", "Trading"], "correct": [1]},
    ],
    # ---------------- Healthcare ----------------
    "agentic-ai-healthcare": [
        {"question": "PHI must be handled under:",
         "options": ["GDPR only", "HIPAA (with BAAs for vendors)", "SOX", "PCI"], "correct": [1]},
        {"question": "FDA classifies AI/ML medical devices under:",
         "options": ["Cosmetics", "Software as a Medical Device (SaMD)",
                     "OTC guidelines", "None"], "correct": [1]},
        {"question": "Which is CRITICAL for clinical-decision-support agents?",
         "type": "multi",
         "options": ["Explainability", "Clinical validation", "Provider-in-the-loop",
                     "Autonomous prescribing"], "correct": [0, 1, 2]},
        {"question": "A BAA is required with:",
         "options": ["Any cafeteria vendor", "Any vendor processing PHI",
                     "GPU vendors always", "No one"], "correct": [1]},
        {"question": "Scenario: Agent summarizes patient chart for physician handoff. Requirement:",
         "type": "scenario",
         "options": ["Auto-diagnose", "PHI-safe pipeline + citations to source note + physician-verified before use",
                     "Public LLM without redaction", "Delete audit logs"], "correct": [1]},
        {"question": "De-identified PHI under HIPAA Safe Harbor requires:",
         "options": ["Removal of 18 identifiers", "Just removing name",
                     "Nothing", "MFA only"], "correct": [0]},
        {"question": "Ambient scribe agents primarily reduce:",
         "options": ["Clinician documentation burden",
                     "Diagnostic accuracy", "Drug efficacy", "Insurance premiums"], "correct": [0]},
        {"question": "FDA's Predetermined Change Control Plan enables:",
         "options": ["Auto-updates without reconformity for anticipated model changes",
                     "Skipping trials", "Zero validation", "Marketing exemptions"], "correct": [0]},
        {"question": "21st Century Cures information-blocking rules affect agents that:",
         "options": ["Interfere with patient EHI access", "Play music", "Do payroll", "Send email"], "correct": [0]},
        {"question": "Clinical validation study for AI SaMD typically covers:",
         "type": "multi",
         "options": ["Analytical validity", "Clinical validity", "Clinical utility",
                     "None of the above"], "correct": [0, 1, 2]},
        {"question": "Consent for AI use in care must be:",
         "options": ["Implied always", "Documented and informed per jurisdiction",
                     "Skipped", "Verbal only"], "correct": [1]},
        {"question": "Which is safest for radiology agent deployment?",
         "options": ["Autonomous reads", "Provider augmentation with explainable outputs + peer review",
                     "Zero validation", "Random"], "correct": [1]},
        {"question": "HIPAA breach notification threshold:",
         "options": ["Never", "500+ affected individuals triggers immediate notice; smaller within 60 days annually",
                     "10k+ only", "1M+ only"], "correct": [1]},
        {"question": "Which risk is UNIQUE to healthcare LLM agents?",
         "options": ["Hallucinating drug interactions with clinical impact",
                     "Slow images", "Font issues", "Battery drain"], "correct": [0]},
        {"question": "Best practice for prompts on clinical agents:",
         "options": ["Cite source documents from EHR context; refuse when out-of-context",
                     "Free-form creativity", "Ignore ontologies", "Skip differentials"], "correct": [0]},
    ],
    # ---------------- Manufacturing ----------------
    "agentic-ai-manufacturing": [
        {"question": "OT/IT boundary is critical because:",
         "options": ["OT systems have real-time safety/availability constraints",
                     "IT is faster", "OT is cheaper", "No difference"], "correct": [0]},
        {"question": "Digital twin agents primarily enable:",
         "type": "multi",
         "options": ["Predictive maintenance", "Simulation-driven optimization",
                     "What-if analysis", "Random shutdowns"], "correct": [0, 1, 2]},
        {"question": "IEC 61508 governs:",
         "options": ["Functional safety of E/E/PE systems", "Marketing", "AI ethics", "GDPR"], "correct": [0]},
        {"question": "Scenario: Agent recommends adjusting a robotic arm mid-shift. Requirement:",
         "type": "scenario",
         "options": ["Auto-execute", "Safety interlock + operator approval + change-log",
                     "Skip logs", "Ignore SIL rating"], "correct": [1]},
        {"question": "MES / SCADA integration for agents typically uses:",
         "options": ["Random APIs", "OPC-UA / MQTT / historian connectors",
                     "USB only", "No integration"], "correct": [1]},
        {"question": "Root-cause analysis agents leverage:",
         "type": "multi",
         "options": ["Ishikawa diagrams", "Time-series anomalies", "5-Why chains",
                     "Zodiac signs"], "correct": [0, 1, 2]},
        {"question": "Predictive maintenance ROI is largest for:",
         "options": ["Low-value equipment", "High-uptime-cost critical assets",
                     "Spare parts", "Water coolers"], "correct": [1]},
        {"question": "Air-gapped LLM deployment is common in:",
         "options": ["Consumer apps", "Defense, aerospace, and OT-critical manufacturing",
                     "E-commerce", "Ad tech"], "correct": [1]},
        {"question": "OT cybersecurity standard often referenced:",
         "options": ["IEC 62443", "SOX", "PCI", "COPPA"], "correct": [0]},
        {"question": "Which agent action requires FUNCTIONAL SAFETY review?",
         "options": ["Reading a dashboard", "Directly commanding a physical actuator",
                     "Formatting a report", "Sending email"], "correct": [1]},
        {"question": "Time-series forecasting agents benefit from:",
         "type": "multi",
         "options": ["Foundation models fine-tuned on time series", "Domain features",
                     "Exogenous variables", "Ignoring seasonality"], "correct": [0, 1, 2]},
        {"question": "Overall Equipment Effectiveness (OEE) improvements from AI typically range:",
         "options": ["5-15%", "50-90%", "Zero", "Negative"], "correct": [0]},
        {"question": "Which is TRUE about industrial AI agents?",
         "type": "true_false",
         "options": ["True — need deterministic fallbacks & human oversight for safety-critical actions",
                     "False — no oversight needed"], "correct": [0]},
        {"question": "Best practice for edge-vs-cloud inference on the shop floor:",
         "options": ["Everything cloud", "Latency-critical & offline-tolerant workloads at the edge",
                     "Everything edge", "Random"], "correct": [1]},
        {"question": "Which log is MANDATORY for regulated manufacturing AI (e.g., pharma GMP)?",
         "options": ["Audit trail of model changes + decisions",
                     "Meme log", "Karaoke log", "None"], "correct": [0]},
    ],
    # ---------------- Retail ----------------
    "agentic-ai-retail": [
        {"question": "Which agent use-case drives fastest ROI in retail?",
         "options": ["Personalized recommendations + dynamic pricing + support automation",
                     "AGI", "Physics simulation", "Blockchain art"], "correct": [0]},
        {"question": "Dynamic pricing agents must respect:",
         "type": "multi",
         "options": ["Legal price-discrimination limits", "Competitive dynamics",
                     "Brand price parity", "Random noise"], "correct": [0, 1, 2]},
        {"question": "Supply-chain planning agents benefit from:",
         "options": ["Demand forecasting + multi-echelon optimization",
                     "Random ordering", "No forecast", "Manual only"], "correct": [0]},
        {"question": "Scenario: Chat agent handles 60% of customer contacts. Requirement:",
         "type": "scenario",
         "options": ["No escalation", "Escalation policies + CSAT tracking + human handoff on regulated topics",
                     "Ignore refunds", "Skip logs"], "correct": [1]},
        {"question": "Recommendation agents primarily optimize:",
         "type": "multi",
         "options": ["Revenue per session", "Diversity/serendipity", "Lifetime value",
                     "Random clicks only"], "correct": [0, 1, 2]},
        {"question": "GS1 standards apply to:",
         "options": ["Product identification (GTIN/barcode) + data standards",
                     "AI models", "GPUs", "Meme formats"], "correct": [0]},
        {"question": "Retail media network agents optimize:",
         "options": ["Ad bidding & creative for sponsored listings",
                     "Payroll", "HR", "OT security"], "correct": [0]},
        {"question": "Which is NOT typical for retail agent guardrails?",
         "options": ["Refund cap", "PII protection", "Autonomous ban of customers",
                     "Rate limits"], "correct": [2]},
        {"question": "Personalization must avoid:",
         "options": ["Discriminatory targeting on protected classes",
                     "Any personalization", "Product images", "Reviews"], "correct": [0]},
        {"question": "In-store agents integrated with CV benefit from:",
         "type": "multi",
         "options": ["Shrink reduction", "Planogram compliance",
                     "Queue optimization", "Random arrests"], "correct": [0, 1, 2]},
        {"question": "Assortment planning improves from:",
         "options": ["Attribute-level demand models + local market signals",
                     "Random selection", "Copying competitors blindly", "Nothing"], "correct": [0]},
        {"question": "Dynamic pricing on grocery staples should:",
         "options": ["Include price-gouging safeguards + regulatory checks",
                     "Maximize prices always", "Freeze prices forever", "Randomize"], "correct": [0]},
        {"question": "Voice-of-customer agents ingest:",
         "type": "multi",
         "options": ["Reviews", "Support tickets", "Survey data", "Weather forecast only"],
         "correct": [0, 1, 2]},
        {"question": "Retail cold-start recommendation problem is best solved with:",
         "options": ["Content-based + hybrid embeddings", "Random", "No recommendations", "SKU count"], "correct": [0]},
        {"question": "Agent-driven promotions must be:",
         "type": "true_false",
         "options": ["True — auditable and reversible", "False — never audit"], "correct": [0]},
    ],
    # ---------------- Government ----------------
    "agentic-ai-government": [
        {"question": "US federal AI use is governed primarily by:",
         "options": ["OMB M-24-10 + NIST AI RMF + agency-specific guidance",
                     "Only NIST", "None", "State laws only"], "correct": [0]},
        {"question": "FedRAMP High is required for:",
         "options": ["Public web pages", "High-impact federal cloud workloads (incl. AI)",
                     "Coffee shops", "None"], "correct": [1]},
        {"question": "Air-gapped LLM deployment is common in:",
         "options": ["Marketing", "Defense, intelligence, and classified environments",
                     "E-commerce", "Meme sites"], "correct": [1]},
        {"question": "Scenario: An agent triages 311 requests for a city. Requirement:",
         "type": "scenario",
         "options": ["Full autonomy", "Human-in-loop for consequential actions + equity audit + accessibility (ADA/508)",
                     "Skip logs", "No accessibility"], "correct": [1]},
        {"question": "Section 508 compliance means:",
         "options": ["ADA electronic accessibility conformance",
                     "Financial audits", "Tax code", "None"], "correct": [0]},
        {"question": "Which are typical procurement requirements for gov AI?",
         "type": "multi",
         "options": ["Data sovereignty", "Auditability",
                     "Bias assessment", "Anonymous vendor identity"], "correct": [0, 1, 2]},
        {"question": "The AI Bill of Rights (US) is:",
         "options": ["Legally binding statute", "Non-binding blueprint from OSTP",
                     "EU regulation", "None"], "correct": [1]},
        {"question": "Freedom of Information Act (FOIA) affects agent-generated records:",
         "type": "true_false",
         "options": ["True — outputs may be FOIA-able", "False — never"], "correct": [0]},
        {"question": "Which is CRITICAL for citizen-facing AI?",
         "options": ["Plain language + multi-language + accessibility",
                     "Only English", "Only via mobile app", "Anonymous only"], "correct": [0]},
        {"question": "Which framework anchors federal AI risk practice?",
         "options": ["NIST AI RMF + AI EO 14110 (as amended) + agency plans",
                     "None", "GDPR alone", "PCI"], "correct": [0]},
        {"question": "For law-enforcement AI use, extra scrutiny is required on:",
         "type": "multi",
         "options": ["Facial recognition accuracy across demographics",
                     "Predictive policing bias", "Warrant requirements",
                     "Marketing budgets"], "correct": [0, 1, 2]},
        {"question": "Data classification levels typically include:",
         "options": ["Unclassified, CUI, Secret, Top Secret",
                     "Only public", "Only secret", "Random"], "correct": [0]},
        {"question": "Government agents must document decisions to enable:",
         "options": ["Congressional oversight + IG audit + FOIA responses",
                     "Marketing", "Random", "None"], "correct": [0]},
        {"question": "Best pattern for benefits-eligibility AI:",
         "options": ["Recommend eligibility + human adjudication + appeal path",
                     "Auto-deny", "Randomize", "Skip appeals"], "correct": [0]},
        {"question": "Bias in agentic AI for government is:",
         "options": ["Especially high-impact given power asymmetry with citizens",
                     "Irrelevant", "Only cost issue", "Never a concern"], "correct": [0]},
    ],
    # ---------------- Executives ----------------
    "generative-ai-executives": [
        {"question": "The primary ROI horizon for well-scoped GenAI pilots is:",
         "options": ["10 years", "3-9 months", "Never", "1 week"], "correct": [1]},
        {"question": "Board-level AI strategy MUST address:",
         "type": "multi",
         "options": ["Governance", "Talent", "Risk appetite", "Only cost"], "correct": [0, 1, 2]},
        {"question": "Which is the STRONGEST AI moat for enterprises?",
         "options": ["A single model choice", "Proprietary data + workflow integration + change management",
                     "Marketing", "GPU count"], "correct": [1]},
        {"question": "AI change-management gap is closed via:",
         "type": "multi",
         "options": ["Role-based reskilling", "Executive sponsorship",
                     "Success stories", "Firing everyone"], "correct": [0, 1, 2]},
        {"question": "Which portfolio approach is proven for enterprise AI?",
         "options": ["70/20/10 (core, adjacent, transformational)",
                     "100% moonshot", "Random", "No portfolio"], "correct": [0]},
        {"question": "Executive KPIs for AI transformation include:",
         "type": "multi",
         "options": ["Cycle-time reduction", "Cost-to-serve", "Employee AI fluency",
                     "GPU count only"], "correct": [0, 1, 2]},
        {"question": "Governance committee cadence should be:",
         "options": ["Monthly minimum + on-demand for high-risk", "Yearly",
                     "Never", "Ad-hoc only"], "correct": [0]},
        {"question": "Which is TRUE about vendor lock-in?",
         "type": "true_false",
         "options": ["True — abstract behind gateways & keep model portability",
                     "False — always pick one vendor"], "correct": [0]},
        {"question": "Fortune 500 CIOs report largest AI barrier as:",
         "options": ["Data readiness + change management",
                     "Model choice", "Meme quality", "GPUs only"], "correct": [0]},
        {"question": "Executive risk owners should sign off on:",
         "type": "multi",
         "options": ["High-risk deployment", "Third-party model use",
                     "Data-crossing decisions", "Coffee brand"], "correct": [0, 1, 2]},
        {"question": "Best approach for measuring AI value:",
         "options": ["Business outcomes + productivity + quality (multi-metric)",
                     "Only cost saved", "Just adoption", "Only NPS"], "correct": [0]},
        {"question": "Talent strategy should include:",
         "options": ["AI fluency for ALL, AI expertise for critical roles",
                     "Fire and rehire", "Ignore talent", "AI-only teams"], "correct": [0]},
        {"question": "Which is a leading indicator of AI transformation health?",
         "options": ["% of decisions made with AI assistance + trust score",
                     "GPU count", "Model count", "Prompt length"], "correct": [0]},
        {"question": "Executive should demand what from AI vendors?",
         "type": "multi",
         "options": ["Model cards", "SOC2/ISO evidence",
                     "Indemnity where feasible", "Random assurances"], "correct": [0, 1, 2]},
        {"question": "AI transformation without workforce upskilling typically:",
         "options": ["Fails to realize value", "Automatically succeeds",
                     "Reduces cost only", "None"], "correct": [0]},
    ],
    # ---------------- LLM Architecture Deep Dive ----------------
    "llm-architecture-deep-dive": [
        {"question": "The Transformer's key innovation is:",
         "options": ["Self-attention replacing recurrence",
                     "GPUs", "Backprop", "SGD"], "correct": [0]},
        {"question": "Mixture-of-Experts (MoE) enables:",
         "options": ["Sparse activation of specialized experts per token",
                     "Denser models", "Smaller vocab", "No training"], "correct": [0]},
        {"question": "RLHF stands for:",
         "options": ["Reinforcement Learning from Human Feedback",
                     "Random Layer Half Freeze", "Rapid LoRA HuggingFace", "None"], "correct": [0]},
        {"question": "KV cache accelerates:",
         "options": ["Autoregressive decoding by caching prior key/value states",
                     "Training", "Embeddings only", "Chunking"], "correct": [0]},
        {"question": "Grouped-query attention (GQA) reduces:",
         "options": ["Memory bandwidth of attention",
                     "Vocab size", "Batch size", "Nothing"], "correct": [0]},
        {"question": "Which is NOT a positional-encoding technique?",
         "options": ["RoPE", "ALiBi", "Sinusoidal", "SGD-Adam"], "correct": [3]},
        {"question": "Speculative decoding uses:",
         "options": ["A draft model to propose tokens, verified by the target model",
                     "Random", "No decoding", "Only greedy"], "correct": [0]},
        {"question": "Which quantization is common for open-weight inference?",
         "type": "multi",
         "options": ["INT8", "INT4", "GPTQ/AWQ", "FP128"],
         "correct": [0, 1, 2]},
        {"question": "Constitutional AI is:",
         "options": ["Anthropic's technique using AI-generated principles + self-critique",
                     "A law", "GPU config", "None"], "correct": [0]},
        {"question": "SFT vs. RLHF vs. DPO — DPO stands for:",
         "options": ["Direct Preference Optimization", "Dense Prompt Overlay",
                     "Domain-Provisioned Objective", "None"], "correct": [0]},
        {"question": "Long-context extension typically leverages:",
         "type": "multi",
         "options": ["RoPE scaling / NTK", "Interpolation", "Sliding windows",
                     "Random truncation"], "correct": [0, 1, 2]},
        {"question": "Rotary Position Embedding (RoPE) applies rotation to:",
         "options": ["Query & key vectors", "Values", "Logits", "Embeddings only"], "correct": [0]},
        {"question": "Which is TRUE about Mixture-of-Experts?",
         "type": "true_false",
         "options": ["True — active parameter count < total params, enabling scale efficiency",
                     "False — every expert runs per token"], "correct": [0]},
        {"question": "Reward hacking in RLHF is:",
         "options": ["Model learns to maximize proxy reward at the expense of true goal",
                     "GPU exploit", "Compute optimization", "None"], "correct": [0]},
        {"question": "State-space models (Mamba, S4) compete with Transformers by:",
         "options": ["Linear scaling with sequence length",
                     "Quadratic scaling", "No attention", "Ignoring inputs"], "correct": [0]},
    ],
    # ---------------- AI Security ----------------
    "ai-security-red-team": [
        {"question": "OWASP LLM Top 10 lists prompt injection as:",
         "options": ["#1", "Ignored", "Only vector DB risk", "None"], "correct": [0]},
        {"question": "Indirect prompt injection exploits:",
         "options": ["Attacker content hidden in retrieved documents / web pages",
                     "Direct user input only", "GPU firmware", "None"], "correct": [0]},
        {"question": "Which is a robust defense against prompt injection?",
         "type": "multi",
         "options": ["Trust boundaries between planner & executor LLMs",
                     "Instruction-tuned models with system-prompt precedence",
                     "Output filtering", "Concatenating user text into system role"],
         "correct": [0, 1, 2]},
        {"question": "Data exfiltration via tools is mitigated by:",
         "options": ["Egress allowlists + DLP + minimum-privilege tools",
                     "Trust all URLs", "No logs", "Random"], "correct": [0]},
        {"question": "Model inversion attacks aim to:",
         "options": ["Recover training data from a model",
                     "Increase throughput", "Add features", "None"], "correct": [0]},
        {"question": "Jailbreaks work primarily via:",
         "options": ["Prompts that override safety training via roleplay/encoding",
                     "GPU exploits", "OS bugs", "None"], "correct": [0]},
        {"question": "Which is a KEY red-team artifact?",
         "options": ["Documented attack playbooks + acceptable-risk matrix",
                     "Only slack messages", "Random", "None"], "correct": [0]},
        {"question": "Tool allowlisting per persona is:",
         "type": "true_false",
         "options": ["True — critical for excessive-agency prevention",
                     "False — never useful"], "correct": [0]},
        {"question": "Which is NOT a supply-chain risk for AI?",
         "options": ["Poisoned model checkpoints", "Malicious dataset",
                     "Compromised prompt template", "Sunny weather"], "correct": [3]},
        {"question": "The dual-LLM pattern separates:",
         "options": ["Privileged reasoning from tainted content processing",
                     "GPU and CPU", "Frontend and DB", "None"], "correct": [0]},
        {"question": "Sensitive-info disclosure risk grows with:",
         "type": "multi",
         "options": ["Overly-broad tool access", "Weak DLP", "Verbose logging with PII",
                     "Strong redaction"], "correct": [0, 1, 2]},
        {"question": "Guardrail libraries include:",
         "options": ["NeMo Guardrails / Guardrails AI / Rebuff",
                     "OpenSSL only", "PyTorch only", "None"], "correct": [0]},
        {"question": "Prompt-injection scanning at inference should:",
         "options": ["Screen both direct AND retrieved content",
                     "Only user input", "Nothing", "Only after"], "correct": [0]},
        {"question": "Incident response for AI needs:",
         "type": "multi",
         "options": ["Kill switches", "Rollback plans", "Post-mortems",
                     "Silence & ignore"], "correct": [0, 1, 2]},
        {"question": "Model theft can happen via:",
         "options": ["Query-based extraction & side-channel leakage",
                     "GPU cost", "Only physical theft", "None"], "correct": [0]},
    ],
    # ---------------- Hospitality ----------------
    "agentic-ai-hospitality": [
        {"question": "Highest-ROI hospitality agent is likely:",
         "options": ["Concierge + dynamic pricing + upsell",
                     "Robot bartender", "AGI", "None"], "correct": [0]},
        {"question": "Dynamic pricing agents integrate with:",
         "type": "multi",
         "options": ["PMS", "Distribution/channel managers",
                     "Competitive rate shops", "Weather app only"], "correct": [0, 1, 2]},
        {"question": "Guest personalization must respect:",
         "options": ["Consent & preferences under privacy law",
                     "None", "Only VIP", "Skip"], "correct": [0]},
        {"question": "Scenario: A hotel AI writes reviews for guests. Best pattern:",
         "type": "scenario",
         "options": ["Auto-submit fake reviews", "Draft only, guest reviews & submits",
                     "Ignore consent", "Randomize"], "correct": [1]},
        {"question": "In multilingual global chains, agents should:",
         "options": ["Localize tone + cultural norms + languages", "English only",
                     "Random", "None"], "correct": [0]},
        {"question": "Distribution parity clauses can be violated by:",
         "options": ["Undercutting rates on direct without OTA parity clauses",
                     "None", "Weather", "Random"], "correct": [0]},
        {"question": "F&B agents optimize:",
         "type": "multi",
         "options": ["Menu engineering", "Wine pairing", "Waste reduction", "Marketing spam"],
         "correct": [0, 1, 2]},
        {"question": "Hospitality chatbots must:",
         "type": "true_false",
         "options": ["True — escalate on regulated topics (health, complaints)",
                     "False — never escalate"], "correct": [0]},
        {"question": "Overbooking agents balance:",
         "options": ["No-show risk vs. compensation cost",
                     "Random", "None", "GPU cost"], "correct": [0]},
        {"question": "Loyalty tier upgrades from AI should be:",
         "options": ["Auditable & rule-anchored", "Random", "Skipped", "Manual only"], "correct": [0]},
        {"question": "Which industry standard applies to hospitality data?",
         "options": ["PCI-DSS (card data) + GDPR/CCPA (guest PII)",
                     "SOX only", "None", "COPPA only"], "correct": [0]},
        {"question": "Concierge agents can improve NPS by:",
         "options": ["Personalized, timely recs + follow-through",
                     "Spamming", "Ignoring", "Random"], "correct": [0]},
        {"question": "Housekeeping optimization agents use:",
         "type": "multi",
         "options": ["IoT sensors", "Booking data",
                     "Guest preferences", "Random dispatch"], "correct": [0, 1, 2]},
        {"question": "AI-powered upsell timing works best:",
         "options": ["Pre-arrival + on-property triggers",
                     "Post-checkout only", "Random", "Never"], "correct": [0]},
        {"question": "Ethical concern with facial-recognition check-in:",
         "options": ["Consent, retention limits, bias",
                     "Speed only", "Cost only", "None"], "correct": [0]},
    ],
    # ---------------- AI Product Management ----------------
    "ai-product-management": [
        {"question": "AI PMs must add which artifact BEYOND typical PM artifacts?",
         "options": ["Model card + eval suite", "Only PRD", "Random", "None"], "correct": [0]},
        {"question": "AI feature discovery should prioritize:",
         "type": "multi",
         "options": ["Data availability", "Value hypothesis",
                     "Failure-mode risk", "GPU count only"], "correct": [0, 1, 2]},
        {"question": "Eval-driven development means:",
         "options": ["Building evals BEFORE ship, treating them as tests",
                     "Ignoring evals", "Random", "None"], "correct": [0]},
        {"question": "Golden datasets should be:",
         "type": "multi",
         "options": ["Representative", "Versioned", "Balanced across cohorts",
                     "Fake data only"], "correct": [0, 1, 2]},
        {"question": "AI PM's north-star metric should:",
         "options": ["Tie AI quality to business outcome",
                     "Only track token count", "GPU hours only", "None"], "correct": [0]},
        {"question": "PRDs for AI need to specify:",
         "type": "multi",
         "options": ["Acceptable error modes", "Fallbacks", "Human oversight",
                     "GPU brand only"], "correct": [0, 1, 2]},
        {"question": "Which is TRUE about AI feature launches?",
         "type": "true_false",
         "options": ["True — canary + rollback + eval regression required",
                     "False — ship & pray"], "correct": [0]},
        {"question": "User trust in AI features improves with:",
         "type": "multi",
         "options": ["Confidence signals", "Citations", "Undo/edit",
                     "Silence about errors"], "correct": [0, 1, 2]},
        {"question": "Cost governance for AI PMs includes:",
         "options": ["Model routing + caching + budget alerts",
                     "Ignoring cost", "Only maximizing quality", "None"], "correct": [0]},
        {"question": "Which is a common AI-PM failure mode?",
         "options": ["Skipping evals & shipping on vibes",
                     "Too many evals", "None", "Random"], "correct": [0]},
        {"question": "OKRs for AI teams should include:",
         "type": "multi",
         "options": ["Quality metrics", "Reliability", "Cost per outcome",
                     "GPU brand"], "correct": [0, 1, 2]},
        {"question": "A/B testing AI features requires:",
         "options": ["Guardrails for both cohorts + stat significance + qualitative review",
                     "Random", "None", "GPU"], "correct": [0]},
        {"question": "Prompt versioning is CRITICAL because:",
         "options": ["Small changes materially change behavior",
                     "None", "GPU cost", "Random"], "correct": [0]},
        {"question": "AI feature success = ",
         "options": ["Value delivered + trust maintained + cost sustainable",
                     "Cost only", "Quality only", "Adoption only"], "correct": [0]},
        {"question": "Which risk framework should AI PMs know?",
         "options": ["NIST AI RMF", "OWASP Web", "PCI only", "None"], "correct": [0]},
    ],
    # ---------------- Enterprise Architecture ----------------
    "ai-architecture-enterprise": [
        {"question": "Reference AI architecture typically includes:",
         "type": "multi",
         "options": ["LLM gateway", "Vector DB", "Feature store", "Coffee machine"],
         "correct": [0, 1, 2]},
        {"question": "LLM gateway provides:",
         "type": "multi",
         "options": ["Model routing", "Semantic caching", "Cost caps + retries",
                     "GPU manufacturing"], "correct": [0, 1, 2]},
        {"question": "Which is a common enterprise AI anti-pattern?",
         "options": ["Direct SDK calls from every microservice without gateway",
                     "Central gateway", "Model portability", "Cost caps"], "correct": [0]},
        {"question": "Zero-trust for AI implies:",
         "options": ["Auth on tool calls + minimum privilege + audit",
                     "Trust everything", "No auth", "Random"], "correct": [0]},
        {"question": "Which is TRUE about multi-tenant AI?",
         "type": "true_false",
         "options": ["True — tenant isolation of data, prompts, and vector namespaces is essential",
                     "False — one shared corpus is fine"], "correct": [0]},
        {"question": "Data mesh + AI works because:",
         "options": ["Domain-owned data + governance + agent-ready contracts",
                     "Random", "GPU only", "None"], "correct": [0]},
        {"question": "Reference latency SLO for interactive AI is often:",
         "options": ["<2s TTFT + streaming",
                     "10 mins", "1 hour", "No SLO"], "correct": [0]},
        {"question": "Which is a fit-for-purpose model routing pattern?",
         "options": ["Cascade: cheap-model first, escalate on low confidence",
                     "Only most expensive model", "Random", "None"], "correct": [0]},
        {"question": "Observability for AI production requires:",
         "type": "multi",
         "options": ["Distributed traces", "Cost per feature",
                     "Quality metrics", "GPU brand only"], "correct": [0, 1, 2]},
        {"question": "Which is essential for AI DR/BC?",
         "options": ["Multi-region model replicas + graceful degradation to smaller model",
                     "None", "Cost only", "Random"], "correct": [0]},
        {"question": "Guardrails should be:",
         "type": "multi",
         "options": ["Layered", "Testable", "Observable", "Invisible & untested"],
         "correct": [0, 1, 2]},
        {"question": "Feature store benefits agentic architectures by:",
         "options": ["Consistent features across offline & online + governance",
                     "None", "Cost only", "Random"], "correct": [0]},
        {"question": "Which is NOT typically in an enterprise LLM reference architecture?",
         "options": ["Consumer app store", "LLM gateway", "Vector DB", "Guardrails"], "correct": [0]},
        {"question": "Streaming SSE endpoints improve:",
         "options": ["Perceived latency for chat", "Model quality", "GPU cost", "None"], "correct": [0]},
        {"question": "Golden path for AI apps at scale includes:",
         "options": ["Starter templates + guardrails + shared infra",
                     "Reinvent every time", "None", "Random"], "correct": [0]},
    ],
    # ---------------- Vector DBs ----------------
    "vector-databases": [
        {"question": "HNSW is a:",
         "options": ["Approximate nearest-neighbor graph index",
                     "SQL engine", "Prompt technique", "None"], "correct": [0]},
        {"question": "IVF-PQ combines:",
         "options": ["Inverted file + product quantization",
                     "SQL + Redis", "Random", "None"], "correct": [0]},
        {"question": "Which is a hybrid search advantage?",
         "options": ["Captures exact & semantic matches (e.g., SKUs)",
                     "None", "Random", "Cost only"], "correct": [0]},
        {"question": "Reranking after ANN top-K:",
         "options": ["Improves precision at low K",
                     "Increases recall only", "Reduces cost", "None"], "correct": [0]},
        {"question": "Choose ALL considerations for VectorDB selection.",
         "type": "multi",
         "options": ["Filter performance", "Multi-tenancy",
                     "Recall@K vs. latency", "GPU brand only"], "correct": [0, 1, 2]},
        {"question": "Cosine vs. dot vs. Euclidean depends on:",
         "options": ["Embedding model's training objective",
                     "Random", "GPU", "None"], "correct": [0]},
        {"question": "Deletion in vector DBs is challenging because:",
         "options": ["Tombstone + reindex or graph repair required",
                     "Never a problem", "Cost only", "None"], "correct": [0]},
        {"question": "Semantic router (Aurelio) is:",
         "options": ["A lightweight intent classifier",
                     "A GPU driver", "A vector index", "None"], "correct": [0]},
        {"question": "Knowledge graphs complement vectors by:",
         "options": ["Multi-hop entity reasoning + explicit relations",
                     "None", "Random", "GPU cost"], "correct": [0]},
        {"question": "Which is TRUE about pgvector?",
         "type": "true_false",
         "options": ["True — good for small-to-medium corpora colocated with relational data",
                     "False — never useful"], "correct": [0]},
        {"question": "Namespaces/tenant partitioning:",
         "options": ["Isolate data & speed filtered search",
                     "None", "Random", "Cost only"], "correct": [0]},
        {"question": "Best chunk size depends on:",
         "type": "multi",
         "options": ["Content type", "Model context window",
                     "Retrieval quality trade-offs", "GPU"], "correct": [0, 1, 2]},
        {"question": "Approximate nearest-neighbor trade-off is:",
         "options": ["Recall vs. speed vs. memory",
                     "None", "Cost only", "GPU"], "correct": [0]},
        {"question": "Vector DB SLA metrics include:",
         "type": "multi",
         "options": ["p99 query latency", "Recall@K",
                     "Ingestion throughput", "GPU brand"], "correct": [0, 1, 2]},
        {"question": "Metadata post-filter vs. pre-filter matters because:",
         "options": ["Pre-filter can dramatically prune the search space",
                     "None", "Random", "Cost only"], "correct": [0]},
    ],
    # ---------------- Fine-tuning ----------------
    "fine-tuning-llms": [
        {"question": "LoRA freezes base weights and trains:",
         "options": ["Low-rank adapters (rank 4-64) on selected layers",
                     "Everything", "Random", "None"], "correct": [0]},
        {"question": "QLoRA additionally uses:",
         "options": ["4-bit quantization of frozen base",
                     "Full precision", "Random", "None"], "correct": [0]},
        {"question": "SFT vs. RLHF: RLHF is used when:",
         "options": ["Aligning to nuanced preferences beyond supervised labels",
                     "Never", "Only cost", "Random"], "correct": [0]},
        {"question": "DPO advantages over PPO include:",
         "type": "multi",
         "options": ["Simpler pipeline", "Stability", "No separate reward model",
                     "Higher GPU cost"], "correct": [0, 1, 2]},
        {"question": "Catastrophic forgetting can be mitigated by:",
         "type": "multi",
         "options": ["Rehearsal / replay data", "LoRA merges",
                     "Adapter routing", "Random"], "correct": [0, 1, 2]},
        {"question": "Fine-tuning is BEST for:",
         "options": ["Behavior/format/style baked into weights",
                     "Fresh knowledge", "Random", "None"], "correct": [0]},
        {"question": "RAG is preferred over FT when:",
         "options": ["Knowledge changes frequently",
                     "Behavior alone matters", "Never", "Random"], "correct": [0]},
        {"question": "Preference data for DPO must include:",
         "options": ["Chosen & rejected pairs",
                     "Only positive", "Only random", "None"], "correct": [0]},
        {"question": "Instruction tuning uses:",
         "options": ["Instruction–response pairs across tasks",
                     "Only completions", "Random", "None"], "correct": [0]},
        {"question": "Merge techniques for adapters include:",
         "type": "multi",
         "options": ["Model soups", "TIES-merging", "DARE",
                     "Random blob"], "correct": [0, 1, 2]},
        {"question": "Fine-tuning small models on task data can:",
         "options": ["Beat larger foundation models on that task at lower cost",
                     "Never help", "Only larger", "Random"], "correct": [0]},
        {"question": "Which eval is CRITICAL post-FT?",
         "options": ["Regression on out-of-domain tasks + safety",
                     "None", "Cost only", "GPU"], "correct": [0]},
        {"question": "Continued pre-training vs. SFT: CPT is for:",
         "options": ["Injecting large amounts of domain corpora into weights",
                     "None", "GPU only", "Random"], "correct": [0]},
        {"question": "Which is TRUE about small SFT datasets?",
         "type": "true_false",
         "options": ["True — even 500-3000 high-quality examples can shift behavior",
                     "False — millions always needed"], "correct": [0]},
        {"question": "Overfitting to synthetic data risks:",
         "options": ["Distributional collapse & artifacts",
                     "Nothing", "GPU cost", "Random"], "correct": [0]},
    ],
    # ---------------- MLOps / AI DevOps ----------------
    "ai-devops-mlops": [
        {"question": "CI for LLM apps must include:",
         "type": "multi",
         "options": ["Prompt/eval regression", "Cost drift check",
                     "Guardrail tests", "Random deploys"], "correct": [0, 1, 2]},
        {"question": "Model registry benefits:",
         "options": ["Version tracking + lineage + rollback",
                     "None", "GPU cost only", "Random"], "correct": [0]},
        {"question": "Blue/green deploy for LLM services enables:",
         "options": ["Instant rollback + canary",
                     "None", "GPU test", "Random"], "correct": [0]},
        {"question": "Prompt versioning tools include:",
         "options": ["Braintrust / PromptLayer / LangSmith",
                     "None", "OpenSSL", "Random"], "correct": [0]},
        {"question": "Golden regression eval should run:",
         "options": ["On every prompt/model change",
                     "Never", "Yearly", "Random"], "correct": [0]},
        {"question": "Observability stack for LLM includes:",
         "type": "multi",
         "options": ["OpenTelemetry", "Prometheus", "Grafana", "None"],
         "correct": [0, 1, 2]},
        {"question": "Cost attribution should be per:",
         "type": "multi",
         "options": ["Team", "Feature", "Customer", "Random"],
         "correct": [0, 1, 2]},
        {"question": "Which is TRUE for GPU capacity planning?",
         "type": "true_false",
         "options": ["True — model routing + spot mix + reserved capacity",
                     "False — only on-demand"], "correct": [0]},
        {"question": "Chaos testing for AI is:",
         "options": ["Injecting failures (tools, models) to test resilience",
                     "None", "Random", "Never"], "correct": [0]},
        {"question": "Feature flags for AI features enable:",
         "options": ["Progressive rollout + kill switches",
                     "None", "GPU control", "Random"], "correct": [0]},
        {"question": "Model card automation on training should:",
         "options": ["Emit standardized artifacts + attach to registry",
                     "Never", "Random", "None"], "correct": [0]},
        {"question": "Semantic caching hit-rate targets:",
         "options": ["Depend on domain; 20-60% is common at scale",
                     "Always 99%", "Never useful", "Random"], "correct": [0]},
        {"question": "AI incident playbooks should cover:",
         "type": "multi",
         "options": ["Data leak", "Cost runaway", "Guardrail bypass",
                     "Coffee outage only"], "correct": [0, 1, 2]},
        {"question": "SLOs for AI apps include:",
         "type": "multi",
         "options": ["Latency", "Quality (eval score)", "Availability",
                     "GPU brand"], "correct": [0, 1, 2]},
        {"question": "Which is NOT typically part of MLOps?",
         "options": ["Data versioning", "CI/CD", "Model registry",
                     "Selling GPUs"], "correct": [3]},
    ],
    # ---------------- AI Change Management ----------------
    "ai-change-management": [
        {"question": "Leading AI change requires:",
         "type": "multi",
         "options": ["Executive sponsorship", "Middle-manager engagement",
                     "Reskilling program", "Fear campaigns"], "correct": [0, 1, 2]},
        {"question": "Kotter's 8-step model applied to AI: first step is:",
         "options": ["Establish urgency", "Ship model", "Random", "None"], "correct": [0]},
        {"question": "Employees adopt AI when:",
         "type": "multi",
         "options": ["Clear value", "Time saved", "Career benefit",
                     "Fear only"], "correct": [0, 1, 2]},
        {"question": "AI reskilling investment ROI is:",
         "options": ["Multi-year but leading indicator of transformation",
                     "None", "Immediate only", "Random"], "correct": [0]},
        {"question": "Which is a proven AI-adoption metric?",
         "options": ["% employees using AI weekly + hours saved reported",
                     "Only NPS", "Only cost", "None"], "correct": [0]},
        {"question": "Comms plan for AI rollout should:",
         "type": "multi",
         "options": ["Address job-security concerns", "Set realistic timelines",
                     "Show success stories", "Only speak to execs"], "correct": [0, 1, 2]},
        {"question": "Which is TRUE about resistance?",
         "type": "true_false",
         "options": ["True — resistance is data; engage & address",
                     "False — ignore and force"], "correct": [0]},
        {"question": "Center of Excellence (CoE) primary role:",
         "options": ["Standards, patterns, enablement across teams",
                     "Sell GPUs", "Ban AI", "None"], "correct": [0]},
        {"question": "Federated vs. centralized AI teams: federated advantage:",
         "options": ["Domain proximity + faster iteration",
                     "None", "Cost only", "Random"], "correct": [0]},
        {"question": "AI ethics training frequency should be:",
         "options": ["At least annual + role-specific",
                     "Never", "Random", "Only new hires"], "correct": [0]},
        {"question": "Change champions network helps by:",
         "options": ["Distributed advocacy + real-user feedback",
                     "None", "Random", "Only marketing"], "correct": [0]},
        {"question": "Executive briefings should focus on:",
         "type": "multi",
         "options": ["Value", "Risk", "Talent",
                     "GPU brand"], "correct": [0, 1, 2]},
        {"question": "Best cadence for AI transformation reviews:",
         "options": ["Quarterly at exec + monthly at ops level",
                     "Never", "Weekly always", "Random"], "correct": [0]},
        {"question": "Employee AI Passport concept enables:",
         "options": ["Portable proof of AI competencies",
                     "None", "Cost", "Random"], "correct": [0]},
        {"question": "Which is a common mistake in AI change management?",
         "options": ["Treating it as a tech-only project",
                     "Communicating too much", "Reskilling", "Governance"], "correct": [0]},
    ],
    # ---------------- Responsible AI ----------------
    "responsible-ai": [
        {"question": "Which fairness metric measures equal outcome rates across groups?",
         "options": ["Demographic parity", "AUC", "F1 only", "None"], "correct": [0]},
        {"question": "Fairness vs. accuracy is:",
         "options": ["Often a trade-off requiring stakeholder alignment",
                     "Never a trade-off", "Random", "None"], "correct": [0]},
        {"question": "Which is a bias-mitigation technique?",
         "type": "multi",
         "options": ["Reweighting", "Adversarial debiasing",
                     "Post-hoc calibration", "Ignoring bias"], "correct": [0, 1, 2]},
        {"question": "Explainability tools include:",
         "type": "multi",
         "options": ["SHAP", "LIME", "Integrated gradients",
                     "Random guesses"], "correct": [0, 1, 2]},
        {"question": "Ethics review for high-risk AI should:",
         "options": ["Include diverse stakeholders + affected community reps",
                     "Only devs", "None", "Random"], "correct": [0]},
        {"question": "Data provenance matters because:",
         "options": ["Determines legal use + bias sources",
                     "None", "Random", "Cost only"], "correct": [0]},
        {"question": "Which framework anchors Responsible AI at scale?",
         "options": ["NIST AI RMF + ISO 42001 + internal ethics charter",
                     "None", "Only GDPR", "Random"], "correct": [0]},
        {"question": "Human oversight is CRITICAL when:",
         "options": ["Decisions have material impact on individuals",
                     "Never", "Only trivial", "Random"], "correct": [0]},
        {"question": "Redress mechanism for AI decisions should include:",
         "type": "multi",
         "options": ["Appeal", "Human review", "Timely response",
                     "Silence"], "correct": [0, 1, 2]},
        {"question": "Which is TRUE about model fairness?",
         "type": "true_false",
         "options": ["True — multiple fairness definitions can be mutually incompatible",
                     "False — one metric fits all"], "correct": [0]},
        {"question": "Data minimization principle from GDPR aligns with:",
         "options": ["Collecting only needed data + purpose limitation",
                     "Maximize", "Random", "None"], "correct": [0]},
        {"question": "AI incident reporting to public should:",
         "options": ["Be proportionate, timely & transparent",
                     "None", "Random", "Never"], "correct": [0]},
        {"question": "Which is a fairness pitfall?",
         "options": ["Proxy variables recreating bias (e.g., ZIP as race proxy)",
                     "None", "Random", "Never"], "correct": [0]},
        {"question": "Ethical AI charters should be:",
         "type": "multi",
         "options": ["Actionable", "Enforced", "Reviewed periodically",
                     "Wall art only"], "correct": [0, 1, 2]},
        {"question": "Right to be forgotten (GDPR Art. 17) means AI systems must:",
         "options": ["Support locate & delete of personal data + downstream artifacts",
                     "Never delete", "Only encrypt", "None"], "correct": [0]},
    ],
    # ---------------- Chief AI Officer Track ----------------
    "chief-ai-officer-track": [
        {"question": "CAIO reports typically to:",
         "options": ["CEO or COO / CTO (varies by org design)",
                     "Only IT", "Only HR", "None"], "correct": [0]},
        {"question": "CAIO's top 3 responsibilities:",
         "type": "multi",
         "options": ["AI strategy & roadmap", "AI governance & risk",
                     "AI talent & culture", "Payroll"], "correct": [0, 1, 2]},
        {"question": "Best org design pattern for AI at scale:",
         "options": ["Federated w/ central CoE",
                     "Fully siloed", "Everyone in one big team", "None"], "correct": [0]},
        {"question": "AI investment portfolio should be:",
         "options": ["Diversified across horizons (H1/H2/H3)",
                     "Only H1", "Only H3", "None"], "correct": [0]},
        {"question": "Which is a CAIO-owned KPI?",
         "options": ["% of BU workflows augmented by AI + realized productivity value",
                     "GPU brand", "Coffee count", "None"], "correct": [0]},
        {"question": "Vendor strategy should:",
         "type": "multi",
         "options": ["Preserve portability", "Enforce guardrails",
                     "Track TCO", "Lock in one vendor"], "correct": [0, 1, 2]},
        {"question": "Which is TRUE about AI M&A?",
         "type": "true_false",
         "options": ["True — capability + team + data are strategic drivers",
                     "False — always avoid"], "correct": [0]},
        {"question": "Talent gap should be closed via:",
         "type": "multi",
         "options": ["Reskilling", "Hiring", "Partnerships",
                     "Ignoring"], "correct": [0, 1, 2]},
        {"question": "Board reporting on AI should cover:",
         "type": "multi",
         "options": ["Value delivered", "Risk posture", "Talent readiness",
                     "GPU count only"], "correct": [0, 1, 2]},
        {"question": "AI ethics escalation path must be:",
         "options": ["Clear, safe, and non-retaliatory",
                     "None", "Random", "Only through HR"], "correct": [0]},
        {"question": "Which is a common CAIO failure?",
         "options": ["Chasing tech without value hypothesis",
                     "Value-driven", "Governance", "None"], "correct": [0]},
        {"question": "External stakeholders CAIOs engage:",
         "type": "multi",
         "options": ["Regulators", "Customers", "Analysts",
                     "None"], "correct": [0, 1, 2]},
        {"question": "AI Bill of Materials (AIBOM) is:",
         "options": ["Inventory of models/data/tools used in AI systems",
                     "None", "Random", "Cost"], "correct": [0]},
        {"question": "CAIO strategy horizon commonly:",
         "options": ["Rolling 3-year with annual re-plan",
                     "Fixed 10-year", "Weekly", "None"], "correct": [0]},
        {"question": "AI OKRs should be:",
         "type": "multi",
         "options": ["Measurable", "Business-linked",
                     "Time-boxed", "Aspirational only"], "correct": [0, 1, 2]},
    ],
    # ---------------- MCP & A2A ----------------
    "mcp-a2a-protocols": [
        {"question": "MCP was introduced by:",
         "options": ["Anthropic", "OpenAI", "Google", "Meta"], "correct": [0]},
        {"question": "MCP's three primitives are:",
         "options": ["Tools, Resources, Prompts", "Weights, Biases, Grads",
                     "GPUs only", "None"], "correct": [0]},
        {"question": "A2A protocol focuses on:",
         "options": ["Agent-to-agent interop across vendors",
                     "GPU sharing", "Random", "None"], "correct": [0]},
        {"question": "MCP transport supports:",
         "type": "multi",
         "options": ["stdio", "HTTP/SSE", "WebSocket-like streams",
                     "SMS only"], "correct": [0, 1, 2]},
        {"question": "Why does MCP matter for enterprises?",
         "options": ["Standardizes tool exposure to any compliant model",
                     "None", "Cost only", "Random"], "correct": [0]},
        {"question": "MCP servers are:",
         "options": ["Processes exposing tools/resources/prompts to clients",
                     "GPU drivers", "None", "Random"], "correct": [0]},
        {"question": "A2A agent card provides:",
         "options": ["Discoverable skill manifest",
                     "None", "Random", "Cost"], "correct": [0]},
        {"question": "Which is TRUE about MCP security?",
         "type": "true_false",
         "options": ["True — untrusted MCP servers must be sandboxed",
                     "False — trust everything"], "correct": [0]},
        {"question": "A2A tasks are:",
         "options": ["Long-running units of work with artifacts",
                     "None", "Random", "Only sync"], "correct": [0]},
        {"question": "Best pattern to combine MCP + A2A:",
         "options": ["Use MCP for tool exposure & A2A for agent orchestration",
                     "None", "Random", "Skip both"], "correct": [0]},
        {"question": "MCP prompt templates enable:",
         "options": ["Reusable interaction patterns exposed by servers",
                     "None", "Random", "Cost only"], "correct": [0]},
        {"question": "Which is NOT an MCP resource?",
         "options": ["A GPU driver", "A file", "A DB row", "An API result"], "correct": [0]},
        {"question": "MCP client responsibilities include:",
         "type": "multi",
         "options": ["Discover", "Authorize tools",
                     "Route to model", "Deploy GPUs"], "correct": [0, 1, 2]},
        {"question": "Multi-modal artifacts in A2A:",
         "options": ["Files, images, code, JSON returned by tasks",
                     "None", "Random", "GPU only"], "correct": [0]},
        {"question": "Standardization impact of MCP+A2A:",
         "options": ["Reduces vendor lock-in for tool & agent ecosystems",
                     "None", "Random", "Only hype"], "correct": [0]},
    ],
    # ---------------- AI Observability ----------------
    "ai-observability": [
        {"question": "TTFT stands for:",
         "options": ["Time to First Token", "Time to Fine-Tune",
                     "Total Fault Tolerance", "None"], "correct": [0]},
        {"question": "Which is a core LLM SLI?",
         "type": "multi",
         "options": ["TTFT", "Tokens/sec", "Cost/req",
                     "GPU brand"], "correct": [0, 1, 2]},
        {"question": "Quality drift is detected by:",
         "options": ["Regression evals + human sampling + telemetry",
                     "None", "Random", "GPU"], "correct": [0]},
        {"question": "Trace linkage across services requires:",
         "options": ["Correlation IDs propagated via OpenTelemetry",
                     "None", "Random", "GPU"], "correct": [0]},
        {"question": "LLM-as-judge pitfalls include:",
         "type": "multi",
         "options": ["Bias to verbose answers", "Model self-preference",
                     "Rubric drift", "None"], "correct": [0, 1, 2]},
        {"question": "Braintrust / LangSmith / Arize primarily provide:",
         "options": ["Traces + evals + prompt management",
                     "GPUs", "None", "Random"], "correct": [0]},
        {"question": "Which is CRITICAL for prod feedback loops?",
         "options": ["Thumbs-up/down + escalation logs + fine-grained tagging",
                     "None", "Random", "GPU"], "correct": [0]},
        {"question": "Which is TRUE about non-determinism?",
         "type": "true_false",
         "options": ["True — replays with seed & params + statistical eval",
                     "False — always deterministic"], "correct": [0]},
        {"question": "Cost telemetry attribute per:",
         "type": "multi",
         "options": ["Feature", "Customer", "Model",
                     "GPU brand"], "correct": [0, 1, 2]},
        {"question": "PII scrubbing at trace level:",
         "options": ["Reduces incident risk + supports compliance",
                     "None", "Random", "Cost"], "correct": [0]},
        {"question": "Golden dataset size for baseline:",
         "options": ["Domain-dependent; 50-500 items common",
                     "10 always", "Millions always", "None"], "correct": [0]},
        {"question": "Regression on model upgrade should:",
         "options": ["Compare on golden set + business-metric shadow test",
                     "Skip", "Random", "None"], "correct": [0]},
        {"question": "Alerting on quality drop should:",
         "options": ["Include severity thresholds + on-call playbook",
                     "None", "Random", "GPU"], "correct": [0]},
        {"question": "Which is a leading indicator of quality issues?",
         "options": ["Rising escalation + drop in thumbs-up + increased tool errors",
                     "None", "Random", "GPU cost"], "correct": [0]},
        {"question": "Log sampling strategy for LLM should:",
         "options": ["Bias toward long-tail + errors while capping cost",
                     "None", "Random", "GPU brand"], "correct": [0]},
    ],
}


async def seed_all():
    total_added = 0
    for slug, items in BANKS.items():
        course = await db.courses.find_one({"slug": slug}, {"_id": 0, "quiz": 1})
        if not course:
            continue
        # Dedupe by question text (case & whitespace normalized) because full-course
        # upserts periodically reset quiz IDs; text is our stable natural key.
        def _norm(t: str) -> str:
            return " ".join((t or "").lower().split())
        existing_texts = {_norm(q.get("question", "")) for q in course.get("quiz", [])}
        candidates = _build(slug, items)
        new_items = [q for q in candidates if _norm(q["question"]) not in existing_texts]
        if not new_items:
            continue
        await db.courses.update_one(
            {"slug": slug},
            {"$push": {"quiz": {"$each": new_items}}},
        )
        total_added += len(new_items)
    logger.info(f"Assessment banks seeded: +{total_added} questions across {len(BANKS)} courses.")
    return total_added
