import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "@/lib/api";
import { RefreshCcw, Radio, Zap, AlertTriangle, ArrowRight, Loader2 } from "lucide-react";

const IMPACT_STYLES = {
    Critical: "bg-destructive text-white",
    High: "bg-brand text-white",
    Medium: "bg-warning text-foreground",
    Low: "bg-surface-alt text-foreground border border-border",
};

const CATEGORY_ICONS = {
    "Model Release": "◈",
    "Framework": "◇",
    "Regulation": "§",
    "Enterprise Deployment": "▶",
    "Research": "∴",
    "Security": "⚡",
    "Standards": "≡",
};

export default function Intelligence() {
    const [briefing, setBriefing] = useState(null);
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);
    const [error, setError] = useState("");

    const load = async (force = false) => {
        setError("");
        force ? setRefreshing(true) : setLoading(true);
        try {
            const res = await api.get("/intelligence/briefing", { params: force ? { force: true } : {} });
            setBriefing(res.data);
        } catch (e) {
            setError(e.response?.data?.detail || "Failed to load briefing.");
        } finally {
            setLoading(false);
            setRefreshing(false);
        }
    };

    useEffect(() => { load(false); }, []);

    return (
        <div>
            {/* Hero */}
            <section className="border-b border-border bg-foreground text-background grain">
                <div className="container-page py-16 md:py-20">
                    <div className="flex items-center gap-3 mb-6">
                        <Radio className="w-5 h-5 text-brand animate-pulse" />
                        <span className="text-[10px] font-mono uppercase tracking-[0.3em] text-brand">ITHR Intelligence Desk · Live</span>
                    </div>
                    <h1 className="font-serif text-5xl md:text-6xl lg:text-7xl tracking-tighter leading-[1.02] mb-6">
                        Weekly signals from<br />
                        the <span className="italic text-brand">agentic frontier.</span>
                    </h1>
                    <p className="text-lg opacity-80 max-w-2xl leading-relaxed">
                        A real-time intelligence briefing generated by ITHR's AI research desk — surfacing model releases, regulation, enterprise deployments, and security signals that materially change what your workforce needs to know. Refreshed every 6 hours.
                    </p>
                </div>
            </section>

            {/* Briefing */}
            <section className="container-page py-16">
                {loading && (
                    <div className="text-center py-20">
                        <Loader2 className="w-8 h-8 animate-spin text-brand mx-auto mb-4" />
                        <p className="text-muted-foreground font-mono text-xs uppercase tracking-[0.2em]">Generating live briefing…</p>
                    </div>
                )}

                {error && !briefing && (
                    <div className="card-flat p-10 text-center">
                        <AlertTriangle className="w-8 h-8 text-brand mx-auto mb-4" />
                        <p className="text-muted-foreground mb-4">{error}</p>
                        <button onClick={() => load(true)} className="btn-outline">Retry</button>
                    </div>
                )}

                {briefing && (
                    <>
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 mb-16 items-end">
                            <div className="md:col-span-8">
                                <div className="overline mb-4 fine-rule pl-4">Today's Briefing</div>
                                <h2 className="font-serif text-3xl md:text-5xl tracking-tighter leading-tight mb-5" data-testid="briefing-title">
                                    {briefing.briefing_title}
                                </h2>
                                <p className="text-lg text-muted-foreground leading-relaxed" data-testid="briefing-summary">
                                    {briefing.executive_summary}
                                </p>
                            </div>
                            <div className="md:col-span-4 md:text-right">
                                <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-muted-foreground mb-2">
                                    {briefing.from_cache ? `Cached · ${briefing.cache_age_hours}h ago` : "Fresh"}
                                </div>
                                <button
                                    onClick={() => load(true)}
                                    disabled={refreshing}
                                    data-testid="refresh-briefing"
                                    className="btn-outline text-sm"
                                >
                                    {refreshing ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCcw className="w-4 h-4" />}
                                    {refreshing ? "Regenerating…" : "Regenerate now"}
                                </button>
                            </div>
                        </div>

                        {/* Signals */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-20">
                            {(briefing.signals || []).map((s) => (
                                <article key={s.id} data-testid={`signal-${s.id}`} className="card-sharp p-7 flex flex-col">
                                    <div className="flex items-start justify-between gap-4 mb-4">
                                        <div className="flex items-center gap-3">
                                            <span className="font-serif text-3xl text-brand leading-none" aria-hidden>{CATEGORY_ICONS[s.category] || "◈"}</span>
                                            <div>
                                                <div className="text-[10px] font-mono uppercase tracking-[0.2em] text-muted-foreground">{s.category}</div>
                                                <div className="text-[10px] font-mono uppercase tracking-[0.15em] text-muted-foreground/70 mt-0.5">{s.source_type}</div>
                                            </div>
                                        </div>
                                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-none text-[10px] font-mono uppercase tracking-[0.15em] ${IMPACT_STYLES[s.impact] || IMPACT_STYLES.Low}`}>
                                            {s.impact}
                                        </span>
                                    </div>

                                    <h3 className="font-serif text-xl leading-tight mb-3">{s.title}</h3>
                                    <p className="text-sm text-muted-foreground leading-relaxed mb-5 flex-1">{s.summary}</p>

                                    <div className="pt-4 border-t border-border">
                                        <div className="overline text-[9px] mb-2 flex items-center gap-1.5">
                                            <Zap className="w-3 h-3" /> Recommended Action
                                        </div>
                                        <p className="text-sm mb-3">{s.recommended_action}</p>

                                        {s.affected_courses?.length > 0 && (
                                            <div className="flex flex-wrap gap-1.5 mt-3">
                                                {s.affected_courses.slice(0, 4).map((slug) => (
                                                    <Link key={slug} to={`/courses/${slug}`} data-testid={`signal-course-${slug}`} className="badge-mono hover:border-brand hover:text-brand transition-colors">
                                                        {slug}
                                                    </Link>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </article>
                            ))}
                        </div>

                        {/* Course refresh priorities */}
                        {briefing.course_refresh_priorities?.length > 0 && (
                            <div className="border-t border-border pt-16">
                                <div className="mb-10 max-w-2xl">
                                    <div className="overline mb-4 fine-rule pl-4">Curriculum Priorities</div>
                                    <h2 className="font-serif text-3xl md:text-4xl tracking-tight leading-tight mb-3">
                                        Courses to refresh — <span className="italic text-brand">in priority order.</span>
                                    </h2>
                                    <p className="text-muted-foreground leading-relaxed">
                                        Curated by the Intelligence Desk based on today's signals. Every course in the ITHR catalog carries a live freshness signal.
                                    </p>
                                </div>

                                <div className="card-flat divide-y divide-border">
                                    {briefing.course_refresh_priorities.map((p, i) => (
                                        <div key={p.course_slug + i} className="grid grid-cols-1 md:grid-cols-12 gap-4 p-6 items-center hover:bg-surface-alt/40 transition-colors" data-testid={`priority-${p.course_slug}`}>
                                            <div className="md:col-span-2">
                                                <span className={`badge-mono ${p.priority === "Now" ? "border-brand text-brand" : p.priority === "This Quarter" ? "border-warning text-warning" : ""}`}>
                                                    {p.priority}
                                                </span>
                                            </div>
                                            <div className="md:col-span-7">
                                                <Link to={`/courses/${p.course_slug}`} className="font-serif text-lg hover:text-brand transition-colors">
                                                    {p.course_slug.replace(/-/g, " ")}
                                                </Link>
                                                <p className="text-sm text-muted-foreground mt-1">{p.reason}</p>
                                            </div>
                                            <div className="md:col-span-3 md:text-right">
                                                <Link to={`/courses/${p.course_slug}`} className="text-sm text-brand hover:underline inline-flex items-center gap-1">
                                                    View course <ArrowRight className="w-4 h-4" />
                                                </Link>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        <div className="mt-20 text-center text-xs text-muted-foreground max-w-2xl mx-auto">
                            Briefing generated by the ITHR Intelligence Desk (Claude Sonnet 4.5). Signals are automatically incorporated into course refresh cycles. All ITHR clients receive daily email digests of new critical-impact signals.
                        </div>
                    </>
                )}
            </section>
        </div>
    );
}
